### ISSUE TITLE
Add support for standard widgets

### ISSUE THREAD

**Issue by kotcrab** [czyzby/gdx-lml-vis#1]
### Widgets extending standard scene2d.ui:
- [x] VisImage
- [x] VisLabel
- [x] VisList
- [x] VisScrollPane
- [x] VisSelectBox
- [x] VisTable
- [x] VisTextButton
- [x] VisTree
- [x] VisWindow
- [x] VisProgressBar
- [x] VisSlider

Those are the easy ones so I guess I will take them.
### Widgets copy-pasted from scene2d.ui:
- [x] VisCheckBox (extends `TextButton`, only draw changed)
  - [x] VisRadioButton (extends `VisCheckBox`)
- [x] VisDialog (extends `VisWindow`)
- [x] VisImageButton (extends `Button`, support for disabling focus border, support for auto generating disabled image)
- [x] VisImageTextButton (extends Button, support for disabling focus border)
- [x] VisSplitPane (extends `WidgetGroup`, only draw changed)
- [x] VisTextField (extends `Widget`, input handling changed, support for disabling focus border, support for marking field as invalid)
  - [x] VisTextArea (nothing changed, extends `VisTextField` to inherit its functionality)

**Comment by czyzby** [comment]
I might have to create base tag classes for widgets from the second group, so I'll take `VisWindow` as well.

**Comment by czyzby** [comment]
I've noticed that `VisProgressBar` and `VisSlider` now extend Scene2D classes, so I've moved them to the first group.

**Comment by czyzby** [comment]
All standard widgets supported, all example templates in tests project now use Vis actors. Closing.
